### ISSUE TITLE
Distance calculation 

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/pickup#2]
Requested in #1 

Currently the manhatten distance is used for all calculations.

The suggestion is to change the Manhatten distance calculations with the "Haversine Manhatten"

"Haversine Manhatten" is the sum of the haversine distance of (lat1, lng1) (lat1, lng2) and (lat1, lng1), (lat2, lng1)
https://medium.com/@simplyjk/why-manhattan-distance-formula-doesnt-apply-to-manhattan-7db0ebb1c5f6

**Comment by wonjoonSeol-WS** [comment]
We can use haversine distance here for distance calculation.
https://en.wikipedia.org/wiki/Haversine_formula

Since we are still not using the road network - haversine manhattan reflects the real world better than the "straight-line" haversine, as euclidean tends to underestimate the actual distance: https://en.wikipedia.org/wiki/Taxicab_geometry

When we are using this the city "angle" is also important - i.e. The angle of the grid for manhattan distance will be based on. For this particular example we can assume the city angle to be 0.

Though please only continue if what you are doing is just for a hobby / toy project. You've helped me far more than what I've originally expected already.

**Comment by JamesBremner** [comment]
I am familiar with the pythagorean or euclidean distance

D = sqrt( dx*dx + dy*dy )

I am familiar with manhatten distance

D = dx + dy

I am familiar with the haversine distance

D = f( lat1, lon1, lat2, lon2 )

I have used all these in various projects.

Note that taxicab == manhatten

"haversine manhattan"  is new to me.  Can you post a link to a detailed description?

**Comment by wonjoonSeol-WS** [comment]
It is the sum of the haversine distance of (lat1, lng1) (lat1, lng2) and (lat1, lng1), (lat2, lng1)
https://medium.com/@simplyjk/why-manhattan-distance-formula-doesnt-apply-to-manhattan-7db0ebb1c5f6

**Comment by JamesBremner** [comment]
Thank you for the nice link!

This would be straightforward to implement, though it would have an impact on performance.  Haversine is a slow way to calculate a distance, and we need to do it twice for every distance.

Are you certain it is worthwhile?  The increase in accuracy is small over the short distances ( < 5km ) we are looking at.  The error introduced by using manhattan distances of any type for a non manhatten city layout ( i.e. London streets ) is very much larger.

Note that application does not care about absolute distances.  It only compares pairs of distances, e.g. to find the rider closest to a restaurant or to optimize the rider's delivery route.  It would be very rare for the change to Haversine calculation to actually change the comparative size of two routes.

**Comment by JamesBremner** [comment]
I have changed all distance calculations to use the static cZone method distance() which allows optional distance calculations to be used.  The default calculation is manhatten.

If you consider it worthwhile to add code for the haversine manhatten calculation, please do so.  ( I assume you know how to fork a github repository, add code, then do a pull request. )

Here is the method where your code can be added

https://github.com/JamesBremner/pickup/blob/a712f65559a400f34ba9e652d6dacf7ab5909eff/src/cZone.cpp#L216-L234

**Comment by wonjoonSeol-WS** [comment]
Yes you are right, for this particular scope we wouldn't need more precise calculation - we are simply interested in riders who is relatively closer so here it does not matter whether we use manhattan or haversine.

In the real world application the rider fee cost is correlated with the distance it needs to travel (Not the actual distance they travel due to potential abusing) so more precise it is the better. This is partially the reason why we want to use road network instead of manhattan.

Since this particular scope does not require more precise absolute distance. You can close the issue.
